export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_LOGOUT = 'LOGIN_USER_LOGOUT';



export const USER_PROFILE_INFORMATION = 'USER_PROFILE_INFORMATION';
export const USER_GET_LOCATION = 'USER_GET_LOCATION';
export const USER_SET_LOCATION = 'USER_SET_LOCATION';
export const USER_SET_MARKER = 'USER_SET_MARKER';


export const DOWNLOAD_INITIALLIST = 'DOWNLOAD_INITIALLIST';
export const DOWNLOAD_INITIALLIST_START = 'DOWNLOAD_INITIALLIST_START';
export const DOWNLOAD_INITIALLIST_SUCCESS = 'DOWNLOAD_INITIALLIST_SUCCESS';

export const FINDLIST_FETCH_START = 'FINDLIST_FETCH_START';
export const FINDLIST_FETCH_SUCCESS = 'FINDLIST_FETCH_SUCCESS';
export const FINDLIST_FETCH_ERROR = 'FINDLIST_FETCH_ERROR';

export const FIND_ADD_START = 'FIND_ADD_START';
export const FIND_ADD_SUCCESS = 'FIND_ADD_SUCCESS';
export const FIND_ADD_ERROR = 'FIND_ADD_ERROR';
export const FIND_REMOVE = 'FIND_REMOVE';

export const SIGNUP_USER_START= 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS= 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL= 'SIGNUP_USER_FAIL';

export const REPORT_FETCH_START = 'REPORT_FETCH_START';
export const REPORT_FETCH_SUCCESS = 'REPORT_FETCH_SUCCESS';
export const REPORT_FETCH_ERROR = 'REPORT_FETCH_ERROR';
export const REPORT_ADD_START= 'REPORT_ADD_START'
export const REPORT_ADD_SUCCESS= 'REPORT_ADD_SUCCESS'
export const REPORT_ADD_ERROR= 'REPORT_ADD_ERROR'
