export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const USER_PROFILE_INFORMATION = 'USER_PROFILE_INFORMATION';
export const USER_GET_LOCATION = 'USER_GET_LOCATION';
export const USER_SET_LOCATION = 'USER_SET_LOCATION';
